<?php

//function bwood_preprocess_node(&$variables) {
  // add node class based on title
  //$variables['classes_array'][] = preg_replace("/\s/", '-', preg_replace("/[^A-Za-z0-9 ]/", '', strtolower($variables['title'])));
//}

// Certificate seal
// drupal_add_js('https://seal.networksolutions.com/siteseal/javascript/siteseal.js', 'external');

function bwood_preprocess(&$variables, $hook) {
  try {
    $variables['is_front'] = \Drupal::service('path.matcher')->isFrontPage();
  }
  catch (Exception $e) {
    $variables['is_front'] = FALSE;
  }
  // Ensure the cache varies correctly (new in Drupal 8.3).
  $variables['#cache']['contexts'][] = 'url.path.is_front';
}

function bwood_preprocess_field__email(&$variables) {
  $variables['items'][0]['content']['#title'] = 'Email';
}
